FROM java:8
EXPOSE 8080:8080
ADD target/spring-boot-demo.jar  spring-boot-demo.jar
ENTRYPOINT ["java","-jar","spring-boot-demo.jar"]
#RUN mkdir /var/dasun
#WORKDIR /var/dasun
#CMD ["pwd"]

#CMD ["echo","hello docker you are awesome,i like it !!!"]

