
server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dasunkanchana2/microservices-course-on-youtube-config-store
          search-paths: 'service-config/*service'
          #repos: